version: "3.9"
    
services:
  db:
    image: mysql:5.7
    #volumes:
    #  - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devoirfinal
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    
  spring:
    depends_on:
      - db
    image:  olanssari/devoirfinal:latest
    ports:
      - "80:8088"
    restart: always
    environment:
      SPRING.DATASOURCE.URL: "jdbc:mysql://db:3306/devoirfinal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC" 
      SPRING.DATASOURCE.USERNAME: "root"
      SPRING.DATASOURCE.PASSWORD: "root"
#volumes:
#  db_data: {}