name: mvn and build image

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  # The goal of this job is compile, test and create the package
  maven_job:
    name: Package
    # odemo is a tag of the Self-hosted runner, to run this Jobs inside the tagged VM
    runs-on: ubuntu-18.04
    # Those jobs are triggered only if the target branch is main
    if: ${{ github.base_ref == 'main' }} 

    steps:
      # checkout to the current branch
      - uses: actions/checkout@v2 
        with:
          ref: ${{ github.head_ref }}
      # set the JDK version
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # run mvn package
      - name: Maven package
        run: mvn clean package -DskipTests
      # upload the jar to use it later when we are building the Docker image
      - name: Upload artifact jar
        uses: actions/upload-artifact@v2
        with:
          name: spring
          path: target/*.jar
      # upload the Dockerfile to use it later when we are building the Docker image
      - name: Upload artifact Dockerfile
        uses: actions/upload-artifact@v2
        with:
          name: Dockerfile
          path: Dockerfile
  # The goal of this job is building a new Docker image using the new package
  push_to_dockerhub:
    name: Building a Docker image and pushing it to DockerHub
    runs-on: ubuntu-18.04
    # this job runs only when the maven_job job is done and succeeded
    needs:
      - maven_job
    steps:
      # download the jar file that we uploaded in the previous job
      - name: Download artifact jar
        uses: actions/download-artifact@v2
        with:
          name: spring
      # download the Dockerfile that we uploaded in the previous job
      - name: Download artifact Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: Dockerfile
      # use the default Buildx configuration
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Login to Dockerhub so we can later push to image
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          # Those params are configured as secrets in the Github repo
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # Build and Push the image to Dockerhub
      - name: Push to Dockerhub registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          # We use the sha of the commit as tag 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devoirfinal:latest